### ISSUE TITLE
apt-key is deprecated

### ISSUE THREAD

**Issue by Andre15711** [lae/ansible-role-proxmox#227] opened 2023-06-24 13:32 UTC
While testing with the pve 8.x keys, I saw this warning.
apt-key module is deprecated. The code needs to be adjusted accordingly.

`TASK [lae.proxmox : Trust Proxmox' packaging key] ****************************************************************************************************************************************************************
fatal: [vm-host2]: FAILED! => changed=false
  cmd: /usr/bin/apt-key add -
  msg: Unable to add a key from binary data
  rc: 2
  stderr: |-
    Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
    gpg: no valid OpenPGP data found.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
`

**Comment by lexxxel** [comment] 2023-06-25 19:53
@Andre15711 this is a duplicate of #226 (you commented on it, too)

**Closed** 2023-08-28 14:20 UTC
