### ISSUE TITLE
Detect sshd service name or make configurable

### ISSUE THREAD

**Issue by aarononeal** [lae/ansible-role-proxmox#187] opened 2022-02-04 21:56 UTC
Handler:
```yaml
- name: reload sshd configuration
  service:
    name: sshd
    state: reloaded
```

Fails with:
`Could not find the requested service sshd: host`

On distros where the service name is `ssh`.

**Comment by lae** [comment] 2022-02-05 02:39
Which Debian version uses a service name of `ssh`?

**Comment by lae** [comment] 2022-02-06 18:55
Closing since I believe this is out of scope and it hasn't been indicated otherwise. This role is intended for use on standard Debian 10 and 11 installations, as that is what Proxmox is based on, which both use `ssh` as the service name as far as I know.

**Comment by aarononeal** [comment] 2022-02-07 17:48
@lae 

Release
```
lsb_release -d
Description:	Debian GNU/Linux 11 (bullseye)
uname -a
Linux node 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64 GNU/Linux
```

Source
```
https://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/
```

```
systemctl status sshd
Unit sshd.service could not be found.
```

```
systemctl status ssh
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; disabled; vendor preset: enabled)
```

**Comment by lae** [comment] 2022-02-07 18:38
Huh. Okay, so first off, this role is tested against up-to-date Debian installs, but that didn't really catch an issue with the service name. So I had to do a bit of sleuthing to understand exactly what's going on.

This is from a live Debian 11 system that's remained up to date:

```
$ systemctl status sshd
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
```

Curiously enough, the actual unit file is named `ssh.service`, and I guess it actually has been like that for a very long time now and I never noticed. The changelog at `/usr/share/doc/openssh-server/changelog.Debian.gz` includes the following:

```
openssh (1:6.5p1-5) unstable; urgency=medium

  [ Colin Watson ]
  * Add Alias=sshd.service to systemd ssh.service file, to match "Provides:
    sshd" in the sysvinit script (thanks, Michael Biebl).
 <snip>

 -- Colin Watson <cjwatson@debian.org>  Wed, 05 Mar 2014 13:53:08 +0000
```

But no reference to removing that `Alias` in the unit file exists, so as far as I understand, `sshd` should still work (and it does for me and I think mostly everyone else), and I confirmed this wasn't an issue with fresh installs back in January when I cut the last release. The `Alias` line is still there in `/lib/systemd/system/ssh.service` and the openssh-server package hasn't had an update since March last year, judging from the changelog.

 I'll attempt to do another build soon to check if it hasn't broken anything, but I wanted to ask you first: can you explain the steps you're taking to go from bare metal (or bare VM) to a the Ansible run that fails? Like, if you're installing from ISO or taking any custom steps, etc.

**Comment by lae** [comment] 2022-02-07 18:44
fwiw since the `ssh` service unit has existed since...pretty much when this role was created, I think we can just rename it in the handler and be done with it. But I am curious as to how your system does not have the alias.

**Comment by aarononeal** [comment] 2022-02-07 19:56
Good find! I didn't realize that was handled with an alias.

It is also in my `/lib/systemd/system/ssh.service` file.

```ini
[Install]
WantedBy=multi-user.target
Alias=sshd.service
```

I see it was under `Install`, so I did this:
```
systemctl enable ssh.service
```

And now it works with the alias:
```
systemctl status sshd
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
```

So it appears this would only be an issue for folks who don't have SSH on boot enabled (an admittedly rare case).

Thank you for pointing me in the right direction.

**Closed** 2022-02-13 13:40 UTC
Labels: invalid
